### PR TITLE
Merge develop branch to master

### PR DESCRIPTION
**Pull request by briankabiro**
The app is 90% done. I need to sort out a few things to get it working

### CODE REVIEW

**Review by kaka-ruto — COMMENTED** [review]
Nice work Brian. Love the commits.

**Comment by briankabiro** [comment]
@borenho Thanks for taking the time and giving me feedback

**Comment by ridgekimani** [comment]
For the travis ci to work, first set your environment to be flask...
env:
  -FLASK=$FLASK_VERSION where $FLASK_VERSION is the version you are currently on eg FLASK=0.10.1

**Comment by ridgekimani** [comment]
For the coveralls it comes after successful travis ci build..
after_success:
  - coveralls

**Comment by ridgekimani** [comment]
And for the coveralls and travis ci to work, you need to have your tests running correctly..

**Comment by RichardMM** [comment]
@briankabiro I like your file structure

**Comment by briankabiro** [comment]
@ridgekimani thanks for the tip

**Comment by briankabiro** [comment]
@RichardMM Thanks

**Pull request merged**
